#!/usr/bin/env bash

if [ "$#" -ne 4 ]; then
    echo "usage: ./qemusz <kernel-src> <debian-image-folder> <debian-distro> <shared-folder>"
    exit 1
fi

KERNEL_SRC=$1
IMAGE_FOLDER=$2
DISTRO=$3
SHARED_FOLDER=$4

qemu-system-x86_64 \
    -s \
    -m 4G \
    -smp 4 \
    -accel kvm \
    -kernel $KERNEL_SRC/arch/x86/boot/bzImage \
    -fsdev local,security_model=mapped,id=fsdev0,path=$SHARED_FOLDER \
    -fsdev local,security_model=mapped,id=fsdev1,path=$KERNEL_SRC \
    -device virtio-9p-pci,id=fs0,fsdev=fsdev0,mount_tag=hostshare \
    -device virtio-9p-pci,id=fs1,fsdev=fsdev1,mount_tag=kernshare \
    -append "console=ttyS0 nokaslr root=/dev/sda" \
    -drive file=$IMAGE_FOLDER/$DISTRO.img,format=raw \
    -net user,host=10.0.2.10,hostfwd=tcp:127.0.0.1:10021-:22 \
    -net nic,model=e1000 \
    -nographic \
